#!/usr/bin/perl
# cpanel - hooks/passwd/change_password.example   Copyright(c) 2009 cPanel, Inc.
#                                                           All rights Reserved.
# copyright@cpanel.net                                         http://cpanel.net

BEGIN { unshift @INC, '/usr/local/cpanel'; }

use XML::Simple;
use Data::Dumper;
use CLI;
use Cpanel::CachedDataStore;

# uid of the user who did the action
my $uid = $ARGV[0];

open (MYFILE, '>>logs/communigate.log');

my $xmldoc;
while (<STDIN>) {
    $xmldoc .= $_;
}
chomp($xmldoc);


if ( substr( $xmldoc, 0, 1 ) ne '<' || substr( $xmldoc, -1, 1 ) ne '>' ) { 
	print MYFILE "$xmldoc is malformed\n";
	die 'XML not well formed'; 
}    # prevent XMLin from opening a file

my $dref           = XMLin($xmldoc);
my $user           = ( getpwuid($uid) )[0];

my $domain 	   = $$dref{'cpanelevent'}{'params'}{'domain'};
my $user= $$dref{'cpanelevent'}{'params'}{'email'};
my $password= $$dref{'cpanelevent'}{'params'}{'password'};
my $quota = $$dref{'cpanelevent'}{'params'}{'quota'};
if ($quota == 0) {
        $quota="unlimited" ;
}else{
        $quota .= "M";
}

my $conf = Cpanel::CachedDataStore::fetch_ref( '/etc/cpanel_cgpro.conf' ) || {};
my $cli = new CGP::CLI( { PeerAddr => $conf->{cgprohost},
                            PeerPort => $conf->{cgproport},
                            login => $conf->{cgprouser},
                            password => $conf->{cgpropass} } );
  unless($cli) {
    print MYFILE "Can't login to CGPro: ".$CGP::ERR_STRING,"\n";
    die("Can't login to CGPro: ".$CGP::ERR_STRING);
}

my $data=$cli->GetDomainSettings("$domain");

if (!$data) {
	$cli->CreateDomain("$domain");
} 
my $UserData;
@$UserData{'Password'}=$password;
@$UserData{'ServiceClass'}="mailonly";
@$UserData{'MaxAccountSize'}=$quota;

$cli->CreateAccount(accountName => "$user\@$domain", settings => $UserData);
$cli->CreateMailbox("$user\@$domain", "Calendar");
$cli->CreateMailbox("$user\@$domain", "Spam");

$cli->Logout();
close (MYFILE);

