#!/usr/bin/perl
# cpanel - hooks/passwd/change_password.example   Copyright(c) 2009 cPanel, Inc.
#                                                           All rights Reserved.
# copyright@cpanel.net                                         http://cpanel.net

BEGIN { unshift @INC, '/usr/local/cpanel'; }

use XML::Simple;
use Data::Dumper;
use CLI;
use Cpanel::CachedDataStore;

# uid of the user who did the action
my $uid = $ARGV[0];

# treat any of the xml data inside the CPDATA tag as trusted
#
# NEVER treat any of the xml data inside the cpanelevent as trusted
# as a malicous user could inject bogus data.
# It's probably never going to be an issue as most people do not want to break
# their own account.


open (MYFILE, '>>logs/communigate.log');

my $xmldoc;
while (<STDIN>) {
    $xmldoc .= $_;
}
chomp($xmldoc);


if ( substr( $xmldoc, 0, 1 ) ne '<' || substr( $xmldoc, -1, 1 ) ne '>' ) { 
	print MYFILE "$xmldoc is malformed\n";
	die 'XML not well formed'; 
}    # prevent XMLin from opening a file

my $dref           = XMLin($xmldoc);
my $user           = ( getpwuid($uid) )[0];

my $domain 	   = $$dref{'cpanelevent'}{'params'}{'domain'};
my $user= $$dref{'cpanelevent'}{'params'}{'email'};
my $pass= $$dref{'cpanelevent'}{'params'}{'password'};

my $conf = Cpanel::CachedDataStore::fetch_ref( '/var/cpanel/communigate.yaml' ) || {};
my $cli = new CGP::CLI( { PeerAddr => $conf->{cgprohost},
                            PeerPort => $conf->{cgproport},
                            login => $conf->{cgprouser},
                            password => $conf->{cgpropass} } );
unless($cli) {
    print MYFILE "Can't login to CGPro: ".$CGP::ERR_STRING,"\n";
    die("Can't login to CGPro: ".$CGP::ERR_STRING);
}

$cli->SetAccountPassword("$user\@$domain","$pass",0);

$cli->Logout();
close (MYFILE);
