#!/usr/local/cpanel/3rdparty/bin/perl

use strict;
use Cpanel::AdminBin::Serializer ();
use Cpanel::Logger               ();
use Cpanel::PwCache              ();
use Cpanel::CachedDataStore      ();
use Cpanel::DnsUtils;

my $stdin = <STDIN>;
chomp $stdin;
my ( $uid, $function, $data ) = split( / /, $stdin, 3 );

# sanitize the input; in this case, only alphanumeric, underscore, space, period, and exclamation are allowed
$data =~ s/![\w \.\!]//g;

# make a note in the logs!
my $user   = ( Cpanel::PwCache::getpwuid($uid) )[0];
my $logger = Cpanel::Logger->new();

if ( $function eq 'GETLOGIN' ) {
    my $conf = Cpanel::CachedDataStore::fetch_ref( '/var/cpanel/communigate.yaml' ) || {};
    print $conf->{cgprohost} , "::" , $conf->{cgproport} , "::" , $conf->{cgprouser} , "::" , $conf->{cgpropass};
    exit(0);
}

elsif ( $function eq 'READFILE' ) {
    my $filename = $data;
    if ( -f $filename) {
	open(FILE, "<", $filename) or die "Failed: $!";
	while (<FILE>) {
	    print $_;
	}
	close(FILE);
    }
    exit(0);
}
elsif ( $function eq 'UNINSTALLSRVXMPP' ) {
    my ($domain,$zone) = split '\|', $data;
    if (-f "/var/named/$zone.db") {
	open(IN, "<", "/var/named/$zone.db") or die "Cannot open zone file ($!)";
	my $out = "";
	for my $row (<IN>) {
	    unless ($row =~ m/^_(xmpp\-(server|client)|jabber)\._tcp\.?$domain\.?\s/) {
		$out .= $row; 
	    }
	}
	close(IN);
	open(OUT, ">", "/var/named/$zone.db") or die "Cannot open zone file ($!)";
	print OUT $out;
	close(OUT);
	print ".";
    } else {
	print "No zone file for domain $domain";
	exit;
    }
    exit(0);
}

elsif ( $function eq 'INSTALLSRVXMPP' ) {
    my ($domain,$zone) = split '\|', $data;
    Cpanel::DnsUtils::install_srv_records( [{'domain' => "$zone",'record' => "_xmpp-server._tcp.$domain", 'value'=> "0 0 5269 mail.$zone."}], [$zone] );
    Cpanel::DnsUtils::install_srv_records( [{'domain' => "$zone",'record' => "_xmpp-client._tcp.$domain", 'value'=> "0 0 5222 mail.$zone."}], [$zone] );
    Cpanel::DnsUtils::install_srv_records( [{'domain' => "$zone",'record' => "_jabber._tcp.$domain", 'value'=> "0 0 5269 mail.$zone."}], [$zone] );
    print ".";
    exit(0);
}

elsif ( $function eq 'UNINSTALLSRVSIP' ) {
    my ($domain,$zone) = split '\|', $data;
    if (-f "/var/named/$zone.db") {
	open(IN, "<", "/var/named/$zone.db") or die "Cannot open zone file ($!)";
	my $out = "";
	for my $row (<IN>) {
	    unless ($row =~ m/^_sip\._udp.?$domain\.?\s/) {
		$out .= $row; 
	    }
	}
	close(IN);
	open(OUT, ">", "/var/named/$zone.db") or die "Cannot open zone file ($!)";
	print OUT $out;
	close(OUT);
	print ".";
    } else {
	print "No zone file for domain $domain";
	exit;
    }
    exit(0);
}

elsif ( $function eq 'INSTALLSRVSIP' ) {
    my ($domain,$zone) = split '\|', $data;
    # "_sip._udp  14400  IN  SRV  1  5  5060  mail.$domain.\n" unless $sip;
    Cpanel::DnsUtils::install_srv_records( [{'domain' => "$zone",'record' => "_sip._udp.$domain", 'value'=> "0 0 5060 mail.$zone."}], [$zone] );
    print ".";
    exit(0);
}

elsif ( $function eq 'UNINSTALLSRVCALDAV' ) {
    my ($domain,$zone) = split '\|', $data;
    if (-f "/var/named/$zone.db") {
	open(IN, "<", "/var/named/$zone.db") or die "Cannot open zone file ($!)";
	my $out = "";
	for my $row (<IN>) {
	    unless ($row =~ m/^_caldavs?\._tcp.?$domain\.?\s/) {
		$out .= $row; 
	    }
	}
	close(IN);
	open(OUT, ">", "/var/named/$zone.db") or die "Cannot open zone file ($!)";
	print OUT $out;
	close(OUT);
	print ".";
    } else {
	print "No zone file for domain $domain";
	exit;
    }
    exit(0);
}

elsif ( $function eq 'INSTALLSRVCALDAV' ) {
    my ($domain,$zone) = split '\|', $data;
    Cpanel::DnsUtils::install_srv_records( [{'domain' => "$zone",'record' => "_caldav._tcp.$domain", 'value'=> "0 0 80 mail.$zone."}], [$zone] );
    Cpanel::DnsUtils::install_srv_records( [{'domain' => "$zone",'record' => "_caldavs._tcp.$domain", 'value'=> "0 0 443 mail.$zone."}], [$zone] );
    print ".";
    # print OUT "_caldav._tcp  14400  IN  SRV  1  5  80  mail.$domain.\n" unless $caldav;
    # print OUT "_caldavs._tcp  14400  IN  SRV  1  5  443  mail.$domain.\n" unless $caldavs;
    exit(0);
}

elsif ( $function eq 'UNINSTALLSRVCARDDAV' ) {
    my ($domain,$zone) = split '\|', $data;
    if (-f "/var/named/$zone.db") {
	open(IN, "<", "/var/named/$zone.db") or die "Cannot open zone file ($!)";
	my $out = "";
	for my $row (<IN>) {
	    unless ($row =~ m/^_carddavs?\._tcp.?$domain\.?\s/) {
		$out .= $row; 
	    }
	}
	close(IN);
	open(OUT, ">", "/var/named/$zone.db") or die "Cannot open zone file ($!)";
	print OUT $out;
	close(OUT);
	print ".";
    } else {
	print "No zone file for domain $domain";
	exit;
    }
    exit(0);
}

elsif ( $function eq 'INSTALLSRVCARDDAV' ) {
    my ($domain,$zone) = split '\|', $data;
    Cpanel::DnsUtils::install_srv_records( [{'domain' => "$zone",'record' => "_carddav._tcp.$domain", 'value'=> "0 0 80 mail.$zone."}], [$zone] );
    Cpanel::DnsUtils::install_srv_records( [{'domain' => "$zone",'record' => "_carddavs._tcp.$domain", 'value'=> "0 0 443 mail.$zone."}], [$zone] );
    print ".";
    # print OUT "_carddav._tcp  14400  IN  SRV  1  5  80  mail.$domain.\n" unless $carddav;
    # print OUT "_carddavs._tcp  14400  IN  SRV  1  5  443  mail.$domain.\n" unless $carddavs;
    exit(1);
}

1;

